# Generated by Django 5.2.8 on 2026-03-18 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_opportunity_assigned_agent_agentprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='api.agentprofile'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='assigned_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_leads', to='api.agentprofile'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('nurturing', 'Nurturing'), ('appointment_set', 'Appointment Set'), ('appointment_held', 'Appointment Held'), ('agreement_signed', 'Agreement Signed'), ('listed_or_showing', 'Listed/Showing'), ('contract_accepted', 'Contract Accepted'), ('closed', 'Listed/Closed'), ('converted', 'Converted to Contact')], db_index=True, default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='stage',
            field=models.CharField(choices=[('prospecting', 'Prospecting'), ('showing', 'Showing'), ('offer_made', 'Offer Made'), ('under_contract', 'Under Contract'), ('closed', 'Closed'), ('appointment_set', 'Appointment Set'), ('appointment_held', 'Appointment Held'), ('agreement_signed', 'Agreement Signed'), ('listed', 'Listed')], default='prospecting', max_length=40),
        ),
    ]
